<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>ServiceDesk.Infrastructure</RootNamespace>
  </PropertyGroup>

  <!-- Required for Identity and Configuration types -->
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ServiceDesk.Application\ServiceDesk.Application.csproj" />
    <ProjectReference Include="..\ServiceDesk.Domain\ServiceDesk.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="10.0.0-preview.*" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.0-preview.*" />
    <PackageReference Include="Minio" Version="6.*" />
  </ItemGroup>

</Project>
