# ==============================================================================
# AI IT Service Desk - Automated Smoke Test Hook
# ==============================================================================
# Purpose: Validates post-deployment health, auth flow, and ticketing operations.
# Configurable via environment variables without hardcoded sensitive secrets.
# Exit code: 0 = ALL PASS, 1 = ANY STEP FAILED.
# ==============================================================================

param(
    [string]$BaseUrl = $env:SERVICE_DESK_BASE_URL,
    [string]$TestEmail = $env:TEST_USER_EMAIL,
    [string]$TestPassword = $env:TEST_USER_PASSWORD
)

if (-not $BaseUrl) { $BaseUrl = "http://localhost" }
if (-not $TestEmail) { $TestEmail = "smoke.tester@internal.company" }
if (-not $TestPassword) { $TestPassword = "SmokeTestPassword123!" }

Write-Host "============================================================" -ForegroundColor Cyan
Write-Host " AI IT Service Desk - Smoke Test Hook Execution" -ForegroundColor Cyan
Write-Host " Base URL   : $BaseUrl" -ForegroundColor Cyan
Write-Host " Test User  : $TestEmail" -ForegroundColor Cyan
Write-Host " Timestamp  : $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')" -ForegroundColor Cyan
Write-Host "============================================================" -ForegroundColor Cyan

$totalSteps = 5
$failedSteps = 0
$createdTicketId = $null
$authToken = $null

function Log-Result {
    param(
        [int]$StepNum,
        [string]$StepName,
        [bool]$Success,
        [string]$Detail
    )
    if ($Success) {
        Write-Host "[$StepNum/$totalSteps] [PASS] $StepName : $Detail" -ForegroundColor Green
    } else {
        Write-Host "[$StepNum/$totalSteps] [FAIL] $StepName : $Detail" -ForegroundColor Red
        $script:failedSteps++
    }
}

# ------------------------------------------------------------------------------
# STEP 1: Verify /health endpoint
# ------------------------------------------------------------------------------
try {
    $healthUrl = "$BaseUrl/health"
    $response = Invoke-WebRequest -Uri $healthUrl -UseBasicParsing -TimeoutSec 10 -ErrorAction Stop
    $statusCode = $response.StatusCode
    $body = $response.Content | ConvertFrom-Json

    if ($statusCode -eq 200 -and $body.status -eq "Healthy") {
        $dbStatus = $body.checks[0].status
        Log-Result -StepNum 1 -StepName "Health Check" -Success $true -Detail "HTTP 200 OK (Status: Healthy, DB: $dbStatus)"
    } else {
        Log-Result -StepNum 1 -StepName "Health Check" -Success $false -Detail "Expected Healthy status, got: $($body.status)"
    }
} catch {
    Log-Result -StepNum 1 -StepName "Health Check" -Success $false -Detail "Request failed: $_"
}

# ------------------------------------------------------------------------------
# STEP 2: Authenticate / Login test account
# ------------------------------------------------------------------------------
try {
    $loginUrl = "$BaseUrl/api/v1/auth/login"
    $loginPayload = @{
        email = $TestEmail
        password = $TestPassword
    } | ConvertTo-Json

    $loginResp = Invoke-WebRequest -Uri $loginUrl -Method Post -Body $loginPayload -ContentType "application/json" -UseBasicParsing -TimeoutSec 10 -ErrorAction Stop
    if ($loginResp.StatusCode -in @(200, 201)) {
        $loginData = $loginResp.Content | ConvertFrom-Json
        $authToken = $loginData.token
        Log-Result -StepNum 2 -StepName "Authentication" -Success $true -Detail "HTTP $($loginResp.StatusCode) Token acquired"
    } else {
        Log-Result -StepNum 2 -StepName "Authentication" -Success $false -Detail "Unexpected HTTP $($loginResp.StatusCode)"
    }
} catch {
    $code = 0
    if ($_.Exception.Response) {
        $code = [int]$_.Exception.Response.StatusCode
    }
    if ($code -eq 404) {
        Log-Result -StepNum 2 -StepName "Authentication" -Success $false -Detail "HTTP 404 Not Found (Auth endpoint not yet implemented in API foundation)"
    } else {
        Log-Result -StepNum 2 -StepName "Authentication" -Success $false -Detail "Auth request failed: $_"
    }
}

# ------------------------------------------------------------------------------
# STEP 3: Create Ticket
# ------------------------------------------------------------------------------
try {
    $ticketUrl = "$BaseUrl/api/v1/tickets"
    $ticketPayload = @{
        title = "Automated Smoke Test Ticket - $(Get-Date -Format 'yyyyMMdd-HHmmss')"
        description = "Automated verification ticket generated by smoke test hook."
        category = "Hardware"
        urgency = "Low"
        impact = "Low"
    } | ConvertTo-Json

    $headers = @{}
    if ($authToken) {
        $headers["Authorization"] = "Bearer $authToken"
    }

    $createResp = Invoke-WebRequest -Uri $ticketUrl -Method Post -Body $ticketPayload -Headers $headers -ContentType "application/json" -UseBasicParsing -TimeoutSec 10 -ErrorAction Stop
    if ($createResp.StatusCode -in @(200, 201)) {
        $ticketData = $createResp.Content | ConvertFrom-Json
        $createdTicketId = $ticketData.id
        Log-Result -StepNum 3 -StepName "Create Ticket" -Success $true -Detail "HTTP $($createResp.StatusCode) Created ticket ID: $createdTicketId"
    } else {
        Log-Result -StepNum 3 -StepName "Create Ticket" -Success $false -Detail "Unexpected HTTP $($createResp.StatusCode)"
    }
} catch {
    $code = 0
    if ($_.Exception.Response) {
        $code = [int]$_.Exception.Response.StatusCode
    }
    if ($code -eq 404) {
        Log-Result -StepNum 3 -StepName "Create Ticket" -Success $false -Detail "HTTP 404 Not Found (Ticket creation endpoint not yet implemented)"
    } else {
        Log-Result -StepNum 3 -StepName "Create Ticket" -Success $false -Detail "Ticket creation failed: $_"
    }
}

# ------------------------------------------------------------------------------
# STEP 4: Get Ticket List
# ------------------------------------------------------------------------------
try {
    $listUrl = "$BaseUrl/api/v1/tickets"
    $headers = @{}
    if ($authToken) {
        $headers["Authorization"] = "Bearer $authToken"
    }

    $listResp = Invoke-WebRequest -Uri $listUrl -Method Get -Headers $headers -UseBasicParsing -TimeoutSec 10 -ErrorAction Stop
    if ($listResp.StatusCode -eq 200) {
        Log-Result -StepNum 4 -StepName "List Tickets" -Success $true -Detail "HTTP 200 OK Retrieved tickets"
    } else {
        Log-Result -StepNum 4 -StepName "List Tickets" -Success $false -Detail "Unexpected HTTP $($listResp.StatusCode)"
    }
} catch {
    $code = 0
    if ($_.Exception.Response) {
        $code = [int]$_.Exception.Response.StatusCode
    }
    if ($code -eq 404) {
        Log-Result -StepNum 4 -StepName "List Tickets" -Success $false -Detail "HTTP 404 Not Found (Ticket listing endpoint not yet implemented)"
    } else {
        Log-Result -StepNum 4 -StepName "List Tickets" -Success $false -Detail "List tickets failed: $_"
    }
}

# ------------------------------------------------------------------------------
# STEP 5: Validate Response Structure & Ticket Verification
# ------------------------------------------------------------------------------
if ($createdTicketId) {
    Log-Result -StepNum 5 -StepName "Response Verification" -Success $true -Detail "Verified ticket ID $createdTicketId in response payload"
} else {
    Log-Result -StepNum 5 -StepName "Response Verification" -Success $false -Detail "Blocked due to prerequisite step failures (endpoints pending implementation)"
}

# ------------------------------------------------------------------------------
# CLEANUP (Idempotent cleanup of test data)
# ------------------------------------------------------------------------------
if ($createdTicketId -and $authToken) {
    Write-Host "`n[CLEANUP] Deleting test ticket $createdTicketId..." -ForegroundColor Yellow
    try {
        Invoke-WebRequest -Uri "$BaseUrl/api/v1/tickets/$createdTicketId" -Method Delete -Headers @{ Authorization = "Bearer $authToken" } -UseBasicParsing -TimeoutSec 10 -ErrorAction SilentlyContinue | Out-Null
        Write-Host "[CLEANUP] Test ticket $createdTicketId removed successfully." -ForegroundColor Green
    } catch {
        Write-Host "[CLEANUP] Note: Test ticket cleanup returned: $_" -ForegroundColor DarkGray
    }
}

Write-Host "============================================================" -ForegroundColor Cyan
if ($failedSteps -gt 0) {
    Write-Host " SMOKE TEST FAILED: $failedSteps / $totalSteps checks failed." -ForegroundColor Red
    Write-Host "============================================================" -ForegroundColor Cyan
    exit 1
} else {
    Write-Host " ALL SMOKE CHECKS PASSED ($totalSteps/$totalSteps)" -ForegroundColor Green
    Write-Host "============================================================" -ForegroundColor Cyan
    exit 0
}
